{% set name = "sqlfluff" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlfluff-{{ version }}.tar.gz
  sha256: e266b3e1e795aa425dc36a42cd5a257721634431f03b899cb891c29451f3a624

build:
  noarch: python
  number: 1
  entry_points:
    - sqlfluff = sqlfluff.cli.commands:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - appdirs
    - backports.cached-property
    - chardet
    - click
    - colorama >=0.3
    - diff-cover >=2.5.0
    - importlib_metadata
    - jinja2
    - pathspec
    - pytest
    - python >=3.7
    - pyyaml >=5.1
    - regex
    - tblib
    - toml
    - tqdm
    - typing_extensions

test:
  source_files:
    - test
  imports:
    - sqlfluff
    - sqlfluff.api
    - sqlfluff.cli
    - sqlfluff.core
    - sqlfluff.core.dialects
    - sqlfluff.core.linter
    - sqlfluff.core.parser
    - sqlfluff.core.parser.grammar
    - sqlfluff.core.parser.segments
    - sqlfluff.core.plugin
    - sqlfluff.core.rules
    - sqlfluff.core.rules.analysis
    - sqlfluff.core.rules.functional
    - sqlfluff.core.templaters
    - sqlfluff.core.templaters.slicers
    - sqlfluff.dialects
    - sqlfluff.rules
    - sqlfluff.testing
  commands:
    - pip check
    - sqlfluff --help
    - pytest -vvv --capture=tee-sys test
  requires:
    - pip
    - pytest

about:
  home: https://www.sqlfluff.com/
  summary: The SQL Linter for Humans
  dev_url: https://github.com/sqlfluff/sqlfluff
  doc_url: https://docs.sqlfluff.com/en/stable/index.html
  license: MIT
  license_file: LICENSE.md
  description: |
    SQLFluff is a dialect-flexible and configurable SQL linter. Designed
     with ELT applications in mind, SQLFluff also works with Jinja
     templating and dbt. SQLFluff will auto-fix most linting errors,
     allowing you to focus your time on what matters.

extra:
  recipe-maintainers:
    - thewchan
